# Generated by Django 4.2.13 on 2026-06-14 06:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_date", models.DateField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("total_items", models.PositiveIntegerField(default=0)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Special instructions or notes"
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, help_text="Admin-only notes"),
                ),
                ("cancelled_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "daily_menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="menu.dailymenu",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DailyOrderReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_orders", models.PositiveIntegerField(default=0)),
                ("total_users", models.PositiveIntegerField(default=0)),
                ("total_items", models.PositiveIntegerField(default=0)),
                (
                    "item_breakdown",
                    models.JSONField(
                        default=dict,
                        help_text="Item-wise quantities: {item_name: {quantity: X, orders: Y, users: Z}}",
                    ),
                ),
                (
                    "category_breakdown",
                    models.JSONField(default=dict, help_text="Category-wise totals"),
                ),
                (
                    "is_finalized",
                    models.BooleanField(
                        default=False,
                        help_text="Report is final (no more changes expected)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "daily_menu",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_report",
                        to="menu.dailymenu",
                    ),
                ),
            ],
            options={
                "db_table": "daily_order_reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField(db_index=True)),
                ("month", models.PositiveIntegerField(db_index=True)),
                (
                    "summary_data",
                    models.JSONField(
                        default=dict, help_text="Aggregated order data for the month"
                    ),
                ),
                ("total_orders", models.PositiveIntegerField(default=0)),
                ("total_items", models.PositiveIntegerField(default=0)),
                ("unique_items_ordered", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_summaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "order_summaries",
                "ordering": ["-year", "-month"],
                "indexes": [
                    models.Index(
                        fields=["user", "year", "month"],
                        name="order_summa_user_id_9a2db8_idx",
                    ),
                    models.Index(
                        fields=["year", "month"], name="order_summa_year_7c0747_idx"
                    ),
                ],
                "unique_together": {("user", "year", "month")},
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=100)),
                ("item_category", models.CharField(max_length=20)),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        help_text="Quantity ordered",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="menu.menuitem",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "db_table": "order_items",
                "ordering": ["menu_item__sort_order", "item_name"],
                "indexes": [
                    models.Index(
                        fields=["order"], name="order_items_order_i_26ad88_idx"
                    ),
                    models.Index(
                        fields=["menu_item"], name="order_items_menu_it_e7a9c0_idx"
                    ),
                    models.Index(
                        fields=["item_name"], name="order_items_item_na_e2a2f3_idx"
                    ),
                ],
                "unique_together": {("order", "menu_item")},
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["user", "order_date"], name="orders_user_id_49d1fd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["daily_menu", "status"], name="orders_daily_m_ee6016_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["order_date", "status"], name="orders_order_d_8ee1f1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["created_at"], name="orders_created_77e2b9_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="order",
            unique_together={("user", "daily_menu")},
        ),
        migrations.AddIndex(
            model_name="dailyorderreport",
            index=models.Index(
                fields=["daily_menu"], name="daily_order_daily_m_be7516_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailyorderreport",
            index=models.Index(
                fields=["is_finalized"], name="daily_order_is_fina_629e82_idx"
            ),
        ),
    ]
