# Generated by Django 4.2.13 on 2026-06-14 06:54

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, unique=True)),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        editable=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=10,
                    ),
                ),
                (
                    "cutoff_time",
                    models.TimeField(
                        default=datetime.time(11, 0),
                        help_text="Time until which orders can be placed",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("total_orders", models.PositiveIntegerField(default=0)),
                ("total_items_ordered", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_daily_menus",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "daily_menus",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="MenuTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        db_index=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_menu_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "menu_templates",
                "ordering": ["weekday", "name"],
            },
        ),
        migrations.CreateModel(
            name="WeeklyMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'Week of June 10-16, 2024'", max_length=100
                    ),
                ),
                ("week_start_date", models.DateField(db_index=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_weekly_menus",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "weekly_menus",
                "ordering": ["-week_start_date"],
            },
        ),
        migrations.CreateModel(
            name="MenuTemplateItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("main", "Main Course"),
                            ("rice", "Rice"),
                            ("curry", "Curry"),
                            ("side", "Side Dish"),
                            ("dessert", "Dessert"),
                            ("beverage", "Beverage"),
                        ],
                        default="main",
                        max_length=20,
                    ),
                ),
                ("max_quantity_per_user", models.PositiveIntegerField(default=5)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_items",
                        to="menu.menutemplate",
                    ),
                ),
            ],
            options={
                "db_table": "menu_template_items",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("main", "Main Course"),
                            ("rice", "Rice"),
                            ("curry", "Curry"),
                            ("side", "Side Dish"),
                            ("dessert", "Dessert"),
                            ("beverage", "Beverage"),
                        ],
                        db_index=True,
                        default="main",
                        max_length=20,
                    ),
                ),
                ("is_available", models.BooleanField(db_index=True, default=True)),
                (
                    "max_quantity_per_user",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Maximum quantity a single user can order",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                ("total_ordered", models.PositiveIntegerField(default=0)),
                ("unique_orders", models.PositiveIntegerField(default=0)),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order in which items appear in menu"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "daily_menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_items",
                        to="menu.dailymenu",
                    ),
                ),
            ],
            options={
                "db_table": "menu_items",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="dailymenu",
            name="weekly_menu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="daily_menus",
                to="menu.weeklymenu",
            ),
        ),
        migrations.AddIndex(
            model_name="weeklymenu",
            index=models.Index(
                fields=["week_start_date"], name="weekly_menu_week_st_bf7a0a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="weeklymenu",
            index=models.Index(
                fields=["is_active"], name="weekly_menu_is_acti_525331_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="menutemplate",
            index=models.Index(
                fields=["weekday", "is_active"], name="menu_templa_weekday_2cc8e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="menuitem",
            index=models.Index(
                fields=["daily_menu", "is_available"],
                name="menu_items_daily_m_b64cbc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="menuitem",
            index=models.Index(
                fields=["category"], name="menu_items_categor_b122d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="menuitem",
            index=models.Index(fields=["name"], name="menu_items_name_1ab05b_idx"),
        ),
        migrations.AddIndex(
            model_name="menuitem",
            index=models.Index(
                fields=["sort_order"], name="menu_items_sort_or_dd867b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailymenu",
            index=models.Index(fields=["date"], name="daily_menus_date_b9eddf_idx"),
        ),
        migrations.AddIndex(
            model_name="dailymenu",
            index=models.Index(fields=["status"], name="daily_menus_status_574ef4_idx"),
        ),
        migrations.AddIndex(
            model_name="dailymenu",
            index=models.Index(
                fields=["weekday"], name="daily_menus_weekday_d7d417_idx"
            ),
        ),
    ]
