# Generated by Django 4.2.13 on 2026-06-14 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dailymenu",
            options={"ordering": ["-date", "meal_type"]},
        ),
        migrations.AlterModelOptions(
            name="menutemplate",
            options={"ordering": ["weekday", "meal_type", "name"]},
        ),
        migrations.RemoveIndex(
            model_name="menutemplate",
            name="menu_templa_weekday_2cc8e6_idx",
        ),
        migrations.AddField(
            model_name="dailymenu",
            name="meal_type",
            field=models.CharField(
                choices=[("lunch", "Lunch"), ("dinner", "Dinner")],
                db_index=True,
                default="lunch",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="menutemplate",
            name="meal_type",
            field=models.CharField(
                choices=[("lunch", "Lunch"), ("dinner", "Dinner")],
                db_index=True,
                default="lunch",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="dailymenu",
            name="cutoff_time",
            field=models.TimeField(
                default=datetime.time(11, 0),
                help_text="Order deadline on the menu date",
            ),
        ),
        migrations.AlterField(
            model_name="dailymenu",
            name="date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="menutemplate",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name="dailymenu",
            index=models.Index(
                fields=["meal_type"], name="daily_menus_meal_ty_a29b3a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailymenu",
            index=models.Index(
                fields=["date", "meal_type"], name="daily_menus_date_212c40_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="menutemplate",
            index=models.Index(
                fields=["weekday", "meal_type", "is_active"],
                name="menu_templa_weekday_fa6918_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="dailymenu",
            constraint=models.UniqueConstraint(
                fields=("date", "meal_type"), name="unique_daily_menu_per_meal"
            ),
        ),
        migrations.AddConstraint(
            model_name="menutemplate",
            constraint=models.UniqueConstraint(
                fields=("weekday", "meal_type"), name="unique_weekday_meal_template"
            ),
        ),
    ]
