# Generated by Django 4.2.13 on 2026-06-14 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_orders", models.PositiveIntegerField(default=0)),
                ("total_items_ordered", models.PositiveIntegerField(default=0)),
                ("average_items_per_order", models.FloatField(default=0.0)),
                ("first_order_date", models.DateField(blank=True, null=True)),
                ("last_order_date", models.DateField(blank=True, null=True)),
                ("days_since_last_order", models.PositiveIntegerField(default=0)),
                (
                    "monthly_breakdown",
                    models.JSONField(default=dict, help_text="Monthly order counts"),
                ),
                (
                    "favorite_items",
                    models.JSONField(
                        default=list, help_text="Most frequently ordered items"
                    ),
                ),
                (
                    "weekday_patterns",
                    models.JSONField(default=dict, help_text="Orders by day of week"),
                ),
                (
                    "is_regular_user",
                    models.BooleanField(default=False, help_text="Orders frequently"),
                ),
                (
                    "is_inactive_user",
                    models.BooleanField(
                        default=False, help_text="Hasn't ordered recently"
                    ),
                ),
                ("last_computed_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_analytics",
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("daily_orders", "Daily Orders Report"),
                            ("weekly_summary", "Weekly Summary"),
                            ("monthly_summary", "Monthly Summary"),
                            ("user_analytics", "User Analytics"),
                            ("item_popularity", "Item Popularity Report"),
                            ("kitchen_requirements", "Kitchen Requirements"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[("json", "JSON"), ("csv", "CSV"), ("xlsx", "Excel")],
                        default="json",
                        max_length=10,
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        default=dict,
                        help_text="Report parameters like date range, filters",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=15,
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to generated report file",
                        max_length=500,
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        default=dict,
                        help_text="Report data if small enough to store in DB",
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requested_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reports",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["report_type", "status"],
                        name="reports_report__f9d8bf_idx",
                    ),
                    models.Index(
                        fields=["requested_by"], name="reports_request_5665b2_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="reports_created_c5f642_idx"
                    ),
                ],
            },
        ),
    ]
